run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gosimple
    - govet
    - gofmt
    - misspell
    - ineffassign
  disable:
    - staticcheck
    - unused

revive:
  rules:
    - name: exported
      disabled: true # Many internal funcs are exported for package access but might not have docs yet

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
